### ISSUE TITLE
Add PDF Viewer to Control Native Downloading and Printing

### ISSUE THREAD

**Issue by plamont** [codeworksdev/digital-sandbox#87]
Incorporate http://viewerjs.org/examples/ into mochi for PDF viewing especially for offline app capabilities.

This will allow control of the Paging, Downloading, Printing and Full Screen modes as well as show PDF in custom dimensions without using the native browser or adobe viewer.

**Comment by codeworksdev** [comment]
This is in the wrong place. Closing this issue.
